//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_AssignmentProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Enrolment = new HashSet<Enrolment>();
        }
    
        public int Id { get; set; }
        [StringLength(30)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z ]*$", ErrorMessage = "Please English words with a capital first letter")]
        public string FirstName { get; set; }
        [StringLength(30)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z ]*$", ErrorMessage = "Please English words with a capital first letter")]
        public string LastName { get; set; }
        [RegularExpression(@"^(?:m|M|male|Male|f|F|female|Female)$", ErrorMessage = "Please enter gender like Male/Female")]
        public string Gender { get; set; }
        [Range(1,110)]
        public string Age { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime Dob { get; set; }
        public int PhoneNumber { get; set; }
        public string Email { get; set; }
        public string UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrolment> Enrolment { get; set; }
    }
}
