//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_AssignmentProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Enrolment = new HashSet<Enrolment>();
        }
    
        public int Id { get; set; }
        [Required]
        [RegularExpression(@"^[A - Za - z] +$",ErrorMessage = "Please enter letters")]
        public string FirstName { get; set; }
        [RegularExpression(@"^[A - Za - z] +$", ErrorMessage = "Please enter letters")]
        [Required]
        [StringLength(20, MinimumLength = 1)]
        public string LastName { get; set; }
        [RegularExpression(@" ^(?:m|M|male|Male|f|F|female|Female)$", ErrorMessage = "Please enter gender like MALE/FEMALE")]
       
        public string Gender { get; set; }
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "Please enter correct age number from 1 to 100")]
        [Range(1,100)]
        public string Age { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime Dob { get; set; }
        public int PhoneNumber { get; set; }
        [RegularExpression(@"^\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$", ErrorMessage = "Please enter valid email address")]
        public string Email { get; set; }
        public string UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrolment> Enrolment { get; set; }
    }
}
