//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_AssignmentProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Unit()
        {
            this.Enrolment = new HashSet<Enrolment>();
        }
    
        public int Id { get; set; }
        public string UnitName { get; set; }
        public string Description { get; set; }
        public decimal PriceAud { get; set; }
        public string UserId { get; set; }
        public int ModuleId { get; set; }
        public int TutorId { get; set; }
        public int ClassRoomId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrolment> Enrolment { get; set; }
        public virtual Module Module { get; set; }
        public virtual Tutor Tutor { get; set; }
        public virtual ClassRoom ClassRoom { get; set; }
    }
}
